import type { Metadata } from "next";
import "../globals.css";
import i18nConfig from "../../../i18nConfig";
import initTranslations from "../i18n";
import { NeoscienceParams } from "@/interfaces/common";
import { dir } from "i18next";
import TranslationsProvider from "@/components/translation-provider";
import styles from "./layout.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

const NAMESPACES_REQUIRED = [
  'menu',
  'footer'
];

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>
}>) {
  const data: NeoscienceParams = await params;
  const { locale, } = data;
  const { t, resources } = await initTranslations(locale as string, NAMESPACES_REQUIRED);

  return (
    <html
      lang={locale}
      dir={dir(locale)}
    >
      <body
        className="antialiased"
        suppressHydrationWarning={true}
      >
        <TranslationsProvider
          namespaces={NAMESPACES_REQUIRED}
          locale={locale}
          resources={resources}
        >
          <body
            className={`antialiased ${styles.wrap}`}
            suppressHydrationWarning
          >

            <header className={styles.header}>
              <div className="container">

                <Header />
              </div>
            </header>

            <main className={styles.main}>
              <div>
                {children}
              </div>
            </main>

            <footer className={styles.footer}>
              <div className="container">
                <Footer t={t} />
              </div>
            </footer>

          </body>
        </TranslationsProvider>
      </body>
    </html>
  );
}
